env:
  global:
    - CC_TEST_REPORTER_ID=7269a2ddb00257b24c1736aa9b465ce3ab94071243b1324a6b74cf8805334594
language: java
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
after_script:
  - cd src/main/java/
  - ../../../cc-test-reporter format-coverage -t jacoco --add-prefix src/main/java/ ../../../build/reports/jacoco/test/jacocoTestReport.xml
  - cd
  - ./cc-test-reporter upload-coverage --input src/main/java/coverage/codeclimate.json
script:
  - ./gradlew check
  - ./gradlew jacocoTestReport
after_success:
  - bash <(curl -s https://codecov.io/bash)